Repository OpenSlides/openslides-meta, pull requests merged in 2024-04, with the labels that each got.

#71 change table names: use appendix "_t"
  dev/sql/schema_relational.sql
  dev/src/helper_get_names.py
Labels: enhancement

#73 use sql only in relaton fields
  dev/sql/schema_relational.sql
  dev/src/generate_sql_schema.py
  dev/tests/base.py
  dev/tests/test_generic_relations.py
  models.yml
Labels: enhancement

#74 Merge `main` into `feature/relational-db`
  .github/workflows/close-issues.yml
  dev/Makefile
Labels: clean up

#72 Add new settings concerning delegator rights
  models.yml
Labels: feature, high

#80 Convert enums to db-constraints and color-type to checked string
  dev/requirements.txt
  dev/sql/schema_relational.sql
  dev/src/db_utils.py
  dev/src/generate_sql_schema.py
  dev/src/helper_get_names.py
  dev/tests/base.py
  dev/tests/test_generic_relations.py
  models.yml
Labels: enhancement

#82 Fixed restriction mode for user is_active.
  models.yml
Labels: staging

#79 Add new setting for topic navigation
  models.yml
Labels: enhancement

#84 Fix models & add rudimentary validation
  .github/workflows/continuous_integration.yml
  dev/sql/schema_relational.sql
  dev/src/validate.py
  models.yml
Labels: enhancement

#85 Add support for self-referencing relations
  dev/sql/schema_relational.sql
  dev/src/generate_sql_schema.py
  models.yml
Labels: feature

#69 Add anchors
  models.yml
Labels: enhancement

#91 Adjust restriction_mode from organization_managment_level
  models.yml
Labels: bug

#93 Add setting to forbid delegator from voting
  models.yml
Labels: feature
