Repository OpenSlides/openslides-meta, pull requests merged in 2024-09, with the labels that each got.

#159 Set all FK to INITIALLY DEFERRED
  dev/sql/schema_relational.sql
  dev/src/generate_sql_schema.py
Labels: feature

#148 remove required-attr from chat_message/meeting_user_id
  models.yml
Labels: bug

#160 Add motion_poll_default_method setting to meeting
  models.yml
Labels: enhancement

#161 Add motion.can_see_origin permission
  models.yml
  permission.yml
Labels: feature

#146 Make changes for public organization mediafiles
  models.yml
Labels: feature, staging, Arrhenius

#167 limit of field name length documented in modesl.yml
  models.yml
Labels: documentation

#165 Give is_active the default true
  models.yml
Labels: bug

#170 newly generated schema_relational.sql
  dev/sql/schema_relational.sql
Labels: enhancement

#173 remove tailing _t from nm- and gm-table names in schema generation
  dev/sql/schema_relational.sql
  dev/src/generate_sql_schema.py
Labels: bug

#116 new gender model
  models.yml
  search.yml
Labels: feature, waiting

#176 Add new meeting setting for motion metadata background
  models.yml
Labels: bug, high

#174 Make changes for self-delegation edit
  models.yml
  permission.yml
Labels: feature
