Repository OpenSlides/openslides-meta, pull requests merged in 2024-02, with the labels that each got.

#5 Apply PEP 585 changes
  models_validator/validate.py
Labels: clean up

#3 Add constant flag
  models.yml
  models_validator/validate.py
Labels: feature

#6 Add fr as possible language
  models.yml
Labels: bug

#7 Add new 100%-base
  models.yml
Labels: feature

#11 Remove anchors and aliases again
  models.yml
Labels: enhancement

#18 Add dev files & setup
  .github/dependabot.yml
  .github/workflows/continuous_integration.yml
  dev/Dockerfile
  dev/Makefile
  dev/docker-compose.yml
  dev/requirements.txt
  dev/setup.cfg
  dev/src/validate.py
  models_validator/requirements.txt
Labels: enhancement

#16 Add changes for los-extension
  models.yml
  permission.yml
Labels: feature, waiting

#20 Update search.yml for los-extension
  search.yml
Labels: feature

#27 Remove VERSION file
  VERSION
Labels: clean up

#21 Rename internal recommendation field
  models.yml
Labels: feature, waiting

#26 Enhance new motion fields
  models.yml
Labels: feature, waiting

#9 Add identical motions relation and hash
  models.yml
Labels: feature, waiting

#14 Allow motion type import preview
  models.yml
Labels: feature

#33 Add new speaker settings
  models.yml
Labels: feature, waiting

#25 Create PRs in all depending repos
  .github/actions/setup-autoupdate-pr.yml
  .github/workflows/announce-file-changes-template.md
  .github/workflows/create-issue-for-file-updates.yml
  .github/workflows/create-pr.yml
  .github/workflows/create-prs-for-updates.yml
Labels: feature

#15 Add changes for user default_number removal
  models.yml
Labels: clean up

#8 Add new user permissions
  models.yml
  permission.yml
Labels: feature
