Repository OpenSlides/openslides-meta, pull requests merged in 2024-08, with the labels that each got.

#123 Enhance motion.create_forwarded
  models.yml
Labels: feature

#133 Make changes for locking out participants
  models.yml
Labels: feature, high, Zeeman

#142 Make changes for custom anonymous group
  models.yml
Labels: feature

#147 Change restriction mode of `active_meeting_ids` to `A`
  models.yml
Labels: feature

#149 merge main into feature/relational db
  dev/requirements.txt
  models.yml
Labels: enhancement

#150 Add reference for foreign key to field meeting/anonymous_group_id
  models.yml
Labels: enhancement

#152 Fix import and generate new relational schema
  dev/sql/schema_relational.sql
  dev/src/generate_sql_schema.py
Labels: bug

#153 Remove idempotency of rel schema
  dev/sql/schema_relational.sql
  dev/src/generate_sql_schema.py
Labels: bug

#154 version upgrade python-sql package to 1.5.1
  dev/requirements.txt
Labels: dependencies

#156 Remove function truncate_tables from relational schema generation
  dev/sql/schema_relational.sql
  dev/src/generate_sql_schema.py
Labels: clean up
