Repository OpenSlides/openslides-meta, pull requests merged in 2024-10, with the labels that each got.

#177 Global enable anonymous
  models.yml
Labels: enhancement, staging

#182 Unify id fields
  models.yml
Labels: clean up

#124 removed statutes
  models.yml
Labels: clean up

#162 Move moderator_notes to list_of_speakers
  models.yml
  permission.yml
Labels: feature
