Repository OpenSlides/openslides-meta, pull requests merged in 2024-07, with the labels that each got.

#113 Make changes for user.merge_together
  models.yml
Labels: feature, staging

#130 make CREATE EXTENSION idempotent
  dev/sql/schema_relational.sql
  dev/src/generate_sql_schema.py
Labels: enhancement

#128 Add new setting for closed meeting
  models.yml
Labels: feature, Curie, Onnes

#129 Add orga setting for duplicate-from mandatory
  models.yml
Labels: feature, Michelson
