Repository OpenSlides/openslides-meta, pull requests merged in 2024-03, with the labels that each got.

#34 Add cascade deletion to new motion fields
  models.yml
Labels: bug

#19 Remove read_only from workflow_timestamp
  models.yml
Labels: feature

#39 Fix searches including users with stucture levels failing
  search.yml
Labels: bug, high

#42 Add staging branches to CI
  .github/workflows/continuous_integration.yml
Labels: enhancement

#37 Implement cascade delete for amendments
  models.yml
Labels: enhancement

#45 Fix milestone ID
  .github/workflows/staging-to-main.yml
Labels: enhancement

#38 Add free text submitter field
  models.yml
  search.yml
Labels: feature, high

#41 Add action to automatically close issues
  .github/workflows/close-issues.yml
Labels: enhancement

#58 Change restriction mode of `user/last_email_sent`
  models.yml
Labels: enhancement

#59 Change restriction modes of username and saml_id
  models.yml
Labels: enhancement

#61 Some setup fixes
  .github/workflows/continuous_integration.yml
  dev/Dockerfile-postgres
  dev/Makefile
  dev/docker-compose.yml
  dev/scripts/apply_db_schema.sh
  dev/scripts/entrypoint.sh
  dev/scripts/wait-for-database.sh
  dev/src/db_utils.py
  dev/src/generate_sql_schema.py
  dev/src/helper_get_names.py
  dev/tests/base.py
Labels: enhancement

#54 Implement new los setting for secondary contributions
  models.yml
Labels: feature

#67 Merge main into feature/relational-db
  .github/workflows/close-issues.yml
  .github/workflows/continuous_integration.yml
  .github/workflows/staging-to-main.yml
  dev/requirements.txt
  models.yml
  search.yml
Labels: clean up
