Repository OpenSlides/openslides-meta, pull requests merged in 2025-07, with the labels that each got.

#277 Use custom sql for relations of user with committee and meeting
  dev/sql/schema_relational.sql
  dev/src/generate_sql_schema.py
  models.yml
Labels: feature

#286 [rel-db] Double precision
  dev/sql/schema_relational.sql
  dev/src/generate_sql_schema.py
Labels: enhancement

#282 Add fields for live voting
  models.yml
Labels: feature

#292 Fix sql comments with quotes
  .github/workflows/test-sql.yml
  dev/scripts/apply_base_data.sh
  dev/scripts/apply_db_schema.sh
  dev/sql/base_data.sql
  dev/sql/schema_relational.sql
  dev/src/generate_sql_schema.py
  models.yml
Labels: bug
