Repository OpenSlides/openslides-meta, pull requests merged in 2025-04, with the labels that each got.

#248 Fix decimal type
  dev/sql/schema_relational.sql
  dev/src/generate_sql_schema.py
Labels: bug, high

#247 Change some values from required to default for easier insert
  models.yml
Labels: clean up

#255 Generate views for all collections
  dev/sql/schema_relational.sql
  dev/src/generate_sql_schema.py
  dev/src/helper_get_names.py
Labels: enhancement

#257 Add motion_state setting for amendment forwarding
  models.yml
Labels: enhancement, high
